CREATE TABLE ACTION (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	user varchar(255) not null,
	verb varchar(20) not null,
	object_uri varchar(255) not null,
	object_type varchar(20) not null,
	create_date timestamp not null default CURRENT_TIMESTAMP
);

insert into ACTION (user, verb, object_uri, object_type) values ('user', 'PLAY', 'http://google.com', 'BOOKMARK');